services:
  gatejoapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatejo-api
    ports:
      - "0:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - ./appsettings.Release.json:/app/appsettings.Release.json:ro
    restart: unless-stopped
