services:
  gatejoapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gatejo-api
    ports:
      - "1406:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__value=
      - Auth__Secret=
      - Auth__ValidAudience=
      - Auth__ValidIssuer=
      - Auth__AccessTokenExpirationMinutes=
      - Auth__RefreshTokenExpirationDays=
    restart: unless-stopped
