services:
  - type: web
    name: gatejo-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    port: 8080
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Release
      - key: ConnectionStrings__value
        sync: false
      - key: Auth__Secret
        sync: false
      - key: Auth__ValidAudience
        sync: false
      - key: Auth__ValidIssuer
        sync: false
      - key: Auth__AccessTokenExpirationMinutes
        sync: false
      - key: Auth__RefreshTokenExpirationDays
        sync: false
